package analizadorlexico;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.util.Hashtable;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Resultados extends javax.swing.JFrame {

    private static LinkedList<String> listaTokens;

    /**
     * Creates new form Resultados
     */
    public Resultados(LinkedList<String> listaTokens) {
        initComponents();
        this.listaTokens = listaTokens;

        Hashtable<String, String[]> simbolos = getSimbolos();
        DefaultTableModel modelSimbolos = (DefaultTableModel) jTableSimbolos.getModel();

        DefaultTableModel model = (DefaultTableModel) jTableTokens.getModel();
        String[] filas = (String[]) listaTokens.toArray(new String[listaTokens.size()]);
        for (String fila : filas) {
            if (simbolos.containsKey(fila)) {
                String[] datos = simbolos.get(fila);
                model.addRow(new String[]{fila, datos[0], datos[1]});
            } else if (fila.matches("^(\\$\\w+)$")) {
                String[] datos = new String[]{fila, "V", "VAR"};
                model.addRow(datos);
                if (!simbolos.containsKey(fila)) {
                    simbolos.put(fila, datos);
                    modelSimbolos.addRow(datos);
                }
            } else if (fila.matches("^('.*')$")) {
                String[] datos = new String[]{fila, "T", "TEX"};
                model.addRow(datos);
                if (!simbolos.containsKey(fila)) {
                    simbolos.put(fila, datos);
                    modelSimbolos.addRow(datos);
                }
            } else if (fila.matches("^(\\d+|(\\d+\\.\\d+))$")) {
                String[] datos = new String[]{fila, "N", "NUM"};
                model.addRow(datos);
                if (!simbolos.containsKey(fila)) {
                    simbolos.put(fila, datos);
                    modelSimbolos.addRow(datos);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Error de análisis: Símbolo \"" + fila + "\" no reconocido", "Error de análisis", JOptionPane.WARNING_MESSAGE);

                WindowEvent wev = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
                Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(wev);
                setVisible(false);
                dispose();

                break;
            }
        }
    }

    private Hashtable<String, String[]> getSimbolos() {
        Hashtable<String, String[]> simbolos = new Hashtable<>();
        simbolos.put("Int", new String[]{"i", "PR"});
        simbolos.put("Float", new String[]{"f", "PR"});
        simbolos.put("Str", new String[]{"s", "PR"});
        simbolos.put("Bool", new String[]{"b", "PR"});
        simbolos.put("print", new String[]{"p", "PR"});
        simbolos.put("input", new String[]{"in", "PR"});
        simbolos.put("compare", new String[]{"c", "PR"});
        simbolos.put("else", new String[]{"e", "PR"});
        simbolos.put("endCompare", new String[]{"ec", "PR"});
        simbolos.put("loop", new String[]{"l", "PR"});
        simbolos.put("endLoop", new String[]{"el", "PR"});
        simbolos.put("programStart", new String[]{"ps", "PR"});
        simbolos.put("programEnd", new String[]{"pe", "PR"});
        simbolos.put("~", new String[]{"~", "SEP"});
        simbolos.put(":", new String[]{":", "SEP"});
        simbolos.put("+", new String[]{"+", "OP"});
        simbolos.put("-", new String[]{"-", "OP"});
        simbolos.put("*", new String[]{"*", "OP"});
        simbolos.put("/", new String[]{"*", "OP"});
        simbolos.put("^", new String[]{"^", "OP"});
        simbolos.put("->", new String[]{"->", "OP"});
        simbolos.put("<>", new String[]{"<>", "OP"});
        simbolos.put("=", new String[]{"=", "OP"});
        simbolos.put("<", new String[]{"<", "OP"});
        simbolos.put(">", new String[]{">", "OP"});
        simbolos.put("ñ", new String[]{"ñ", "OP"});
        simbolos.put("??", new String[]{"??", "COM"});
        simbolos.put("¿", new String[]{"¿", "COM"});
        simbolos.put("?", new String[]{"?", "COM"});
        return simbolos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelSimbolos = new javax.swing.JLabel();
        jScrollPaneSimbolos = new javax.swing.JScrollPane();
        jTableSimbolos = new javax.swing.JTable();
        jLabelTokens = new javax.swing.JLabel();
        jScrollPaneTokens = new javax.swing.JScrollPane();
        jTableTokens = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelSimbolos.setText("Tabla Símbolos");

        jTableSimbolos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Int", "i", "PR"},
                {"Float", "f", "PR"},
                {"Str", "s", "PR"},
                {"Bool", "b", "PR"},
                {"print", "p", "PR"},
                {"input", "in", "PR"},
                {"compare", "c", "PR"},
                {"else", "e", "PR"},
                {"endCompare", "ec", "PR"},
                {"loop", "l", "PR"},
                {"endLoop", "el", "PR"},
                {"programStart", "ps", "PR"},
                {"programEnd", "pe", "PR"},
                {"~", "~", "SEP"},
                {":", ":", "SEP"},
                {"+", "+", "OP"},
                {"-", "-", "OP"},
                {"*", "*", "OP"},
                {"/", "/", "OP"},
                {"^", "^", "OP"},
                {"->", "->", "OP"},
                {"<>", "<>", "OP"},
                {"=", "=", "OP"},
                {"<", "<", "OP"},
                {">", ">", "OP"},
                {"ñ", "ñ", "OP"},
                {"??", "??", "COM"},
                {"¿", "¿", "COM"},
                {"?", "¿", "COM"}
            },
            new String [] {
                "Lexema", "Identificador", "Categoría"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableSimbolos.setMinimumSize(new java.awt.Dimension(0, 200));
        jScrollPaneSimbolos.setViewportView(jTableSimbolos);

        jLabelTokens.setText("Tabla Tokens");

        jTableTokens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lexema", "Identificador", "Categoría"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTokens.setMinimumSize(new java.awt.Dimension(0, 200));
        jScrollPaneTokens.setViewportView(jTableTokens);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneSimbolos, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSimbolos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneTokens, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTokens))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSimbolos)
                    .addComponent(jLabelTokens))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPaneSimbolos)
                    .addComponent(jScrollPaneTokens))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Resultados(listaTokens).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelSimbolos;
    private javax.swing.JLabel jLabelTokens;
    private javax.swing.JScrollPane jScrollPaneSimbolos;
    private javax.swing.JScrollPane jScrollPaneTokens;
    private javax.swing.JTable jTableSimbolos;
    private javax.swing.JTable jTableTokens;
    // End of variables declaration//GEN-END:variables
}
